// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: action.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 7000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "pose.capnp.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(ebb0fc0b37fcaba4);
CAPNP_DECLARE_SCHEMA(f1d090b2c3bf545e);

}  // namespace schemas
}  // namespace capnp

namespace vpp_msg {

struct RandomizationParameters {
  RandomizationParameters() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(ebb0fc0b37fcaba4, 1, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Action {
  Action() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    NONE,
    RESET,
    RELATIVE_JOINT_TARGET,
    ABSOLUTE_JOINT_TARGET,
    GOAL_POSE,
    RELATIVE_POSE,
    RESET_AND_RANDOMIZE,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f1d090b2c3bf545e, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class RandomizationParameters::Reader {
public:
  typedef RandomizationParameters Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasMin() const;
  inline  ::vpp_msg::Point::Reader getMin() const;

  inline bool hasMax() const;
  inline  ::vpp_msg::Point::Reader getMax() const;

  inline double getMinDist() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class RandomizationParameters::Builder {
public:
  typedef RandomizationParameters Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasMin();
  inline  ::vpp_msg::Point::Builder getMin();
  inline void setMin( ::vpp_msg::Point::Reader value);
  inline  ::vpp_msg::Point::Builder initMin();
  inline void adoptMin(::capnp::Orphan< ::vpp_msg::Point>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Point> disownMin();

  inline bool hasMax();
  inline  ::vpp_msg::Point::Builder getMax();
  inline void setMax( ::vpp_msg::Point::Reader value);
  inline  ::vpp_msg::Point::Builder initMax();
  inline void adoptMax(::capnp::Orphan< ::vpp_msg::Point>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Point> disownMax();

  inline double getMinDist();
  inline void setMinDist(double value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class RandomizationParameters::Pipeline {
public:
  typedef RandomizationParameters Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::vpp_msg::Point::Pipeline getMin();
  inline  ::vpp_msg::Point::Pipeline getMax();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Action::Reader {
public:
  typedef Action Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isNone() const;
  inline  ::capnp::Void getNone() const;

  inline bool isReset() const;
  inline  ::capnp::Void getReset() const;

  inline bool isRelativeJointTarget() const;
  inline bool hasRelativeJointTarget() const;
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader getRelativeJointTarget() const;

  inline bool isAbsoluteJointTarget() const;
  inline bool hasAbsoluteJointTarget() const;
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader getAbsoluteJointTarget() const;

  inline bool isGoalPose() const;
  inline bool hasGoalPose() const;
  inline  ::vpp_msg::Pose::Reader getGoalPose() const;

  inline bool isRelativePose() const;
  inline bool hasRelativePose() const;
  inline  ::vpp_msg::Pose::Reader getRelativePose() const;

  inline bool isResetAndRandomize() const;
  inline bool hasResetAndRandomize() const;
  inline  ::vpp_msg::RandomizationParameters::Reader getResetAndRandomize() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Action::Builder {
public:
  typedef Action Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isNone();
  inline  ::capnp::Void getNone();
  inline void setNone( ::capnp::Void value = ::capnp::VOID);

  inline bool isReset();
  inline  ::capnp::Void getReset();
  inline void setReset( ::capnp::Void value = ::capnp::VOID);

  inline bool isRelativeJointTarget();
  inline bool hasRelativeJointTarget();
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder getRelativeJointTarget();
  inline void setRelativeJointTarget( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setRelativeJointTarget(::kj::ArrayPtr<const double> value);
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder initRelativeJointTarget(unsigned int size);
  inline void adoptRelativeJointTarget(::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> disownRelativeJointTarget();

  inline bool isAbsoluteJointTarget();
  inline bool hasAbsoluteJointTarget();
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder getAbsoluteJointTarget();
  inline void setAbsoluteJointTarget( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setAbsoluteJointTarget(::kj::ArrayPtr<const double> value);
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder initAbsoluteJointTarget(unsigned int size);
  inline void adoptAbsoluteJointTarget(::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> disownAbsoluteJointTarget();

  inline bool isGoalPose();
  inline bool hasGoalPose();
  inline  ::vpp_msg::Pose::Builder getGoalPose();
  inline void setGoalPose( ::vpp_msg::Pose::Reader value);
  inline  ::vpp_msg::Pose::Builder initGoalPose();
  inline void adoptGoalPose(::capnp::Orphan< ::vpp_msg::Pose>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Pose> disownGoalPose();

  inline bool isRelativePose();
  inline bool hasRelativePose();
  inline  ::vpp_msg::Pose::Builder getRelativePose();
  inline void setRelativePose( ::vpp_msg::Pose::Reader value);
  inline  ::vpp_msg::Pose::Builder initRelativePose();
  inline void adoptRelativePose(::capnp::Orphan< ::vpp_msg::Pose>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Pose> disownRelativePose();

  inline bool isResetAndRandomize();
  inline bool hasResetAndRandomize();
  inline  ::vpp_msg::RandomizationParameters::Builder getResetAndRandomize();
  inline void setResetAndRandomize( ::vpp_msg::RandomizationParameters::Reader value);
  inline  ::vpp_msg::RandomizationParameters::Builder initResetAndRandomize();
  inline void adoptResetAndRandomize(::capnp::Orphan< ::vpp_msg::RandomizationParameters>&& value);
  inline ::capnp::Orphan< ::vpp_msg::RandomizationParameters> disownResetAndRandomize();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Action::Pipeline {
public:
  typedef Action Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool RandomizationParameters::Reader::hasMin() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool RandomizationParameters::Builder::hasMin() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Point::Reader RandomizationParameters::Reader::getMin() const {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Point::Builder RandomizationParameters::Builder::getMin() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vpp_msg::Point::Pipeline RandomizationParameters::Pipeline::getMin() {
  return  ::vpp_msg::Point::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void RandomizationParameters::Builder::setMin( ::vpp_msg::Point::Reader value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Point>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Point::Builder RandomizationParameters::Builder::initMin() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void RandomizationParameters::Builder::adoptMin(
    ::capnp::Orphan< ::vpp_msg::Point>&& value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Point>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Point> RandomizationParameters::Builder::disownMin() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool RandomizationParameters::Reader::hasMax() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool RandomizationParameters::Builder::hasMax() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Point::Reader RandomizationParameters::Reader::getMax() const {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Point::Builder RandomizationParameters::Builder::getMax() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vpp_msg::Point::Pipeline RandomizationParameters::Pipeline::getMax() {
  return  ::vpp_msg::Point::Pipeline(_typeless.getPointerField(1));
}
#endif  // !CAPNP_LITE
inline void RandomizationParameters::Builder::setMax( ::vpp_msg::Point::Reader value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Point>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Point::Builder RandomizationParameters::Builder::initMax() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void RandomizationParameters::Builder::adoptMax(
    ::capnp::Orphan< ::vpp_msg::Point>&& value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Point>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Point> RandomizationParameters::Builder::disownMax() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Point>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline double RandomizationParameters::Reader::getMinDist() const {
  return _reader.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline double RandomizationParameters::Builder::getMinDist() {
  return _builder.getDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void RandomizationParameters::Builder::setMinDist(double value) {
  _builder.setDataField<double>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::vpp_msg::Action::Which Action::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::vpp_msg::Action::Which Action::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool Action::Reader::isNone() const {
  return which() == Action::NONE;
}
inline bool Action::Builder::isNone() {
  return which() == Action::NONE;
}
inline  ::capnp::Void Action::Reader::getNone() const {
  KJ_IREQUIRE((which() == Action::NONE),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Action::Builder::getNone() {
  KJ_IREQUIRE((which() == Action::NONE),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Action::Builder::setNone( ::capnp::Void value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::NONE);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Action::Reader::isReset() const {
  return which() == Action::RESET;
}
inline bool Action::Builder::isReset() {
  return which() == Action::RESET;
}
inline  ::capnp::Void Action::Reader::getReset() const {
  KJ_IREQUIRE((which() == Action::RESET),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Action::Builder::getReset() {
  KJ_IREQUIRE((which() == Action::RESET),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Action::Builder::setReset( ::capnp::Void value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RESET);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Action::Reader::isRelativeJointTarget() const {
  return which() == Action::RELATIVE_JOINT_TARGET;
}
inline bool Action::Builder::isRelativeJointTarget() {
  return which() == Action::RELATIVE_JOINT_TARGET;
}
inline bool Action::Reader::hasRelativeJointTarget() const {
  if (which() != Action::RELATIVE_JOINT_TARGET) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Action::Builder::hasRelativeJointTarget() {
  if (which() != Action::RELATIVE_JOINT_TARGET) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader Action::Reader::getRelativeJointTarget() const {
  KJ_IREQUIRE((which() == Action::RELATIVE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Action::Builder::getRelativeJointTarget() {
  KJ_IREQUIRE((which() == Action::RELATIVE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::setRelativeJointTarget( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void Action::Builder::setRelativeJointTarget(::kj::ArrayPtr<const double> value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Action::Builder::initRelativeJointTarget(unsigned int size) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_JOINT_TARGET);
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Action::Builder::adoptRelativeJointTarget(
    ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> Action::Builder::disownRelativeJointTarget() {
  KJ_IREQUIRE((which() == Action::RELATIVE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Action::Reader::isAbsoluteJointTarget() const {
  return which() == Action::ABSOLUTE_JOINT_TARGET;
}
inline bool Action::Builder::isAbsoluteJointTarget() {
  return which() == Action::ABSOLUTE_JOINT_TARGET;
}
inline bool Action::Reader::hasAbsoluteJointTarget() const {
  if (which() != Action::ABSOLUTE_JOINT_TARGET) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Action::Builder::hasAbsoluteJointTarget() {
  if (which() != Action::ABSOLUTE_JOINT_TARGET) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader Action::Reader::getAbsoluteJointTarget() const {
  KJ_IREQUIRE((which() == Action::ABSOLUTE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Action::Builder::getAbsoluteJointTarget() {
  KJ_IREQUIRE((which() == Action::ABSOLUTE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::setAbsoluteJointTarget( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::ABSOLUTE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void Action::Builder::setAbsoluteJointTarget(::kj::ArrayPtr<const double> value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::ABSOLUTE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Action::Builder::initAbsoluteJointTarget(unsigned int size) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::ABSOLUTE_JOINT_TARGET);
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Action::Builder::adoptAbsoluteJointTarget(
    ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::ABSOLUTE_JOINT_TARGET);
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> Action::Builder::disownAbsoluteJointTarget() {
  KJ_IREQUIRE((which() == Action::ABSOLUTE_JOINT_TARGET),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Action::Reader::isGoalPose() const {
  return which() == Action::GOAL_POSE;
}
inline bool Action::Builder::isGoalPose() {
  return which() == Action::GOAL_POSE;
}
inline bool Action::Reader::hasGoalPose() const {
  if (which() != Action::GOAL_POSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Action::Builder::hasGoalPose() {
  if (which() != Action::GOAL_POSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Pose::Reader Action::Reader::getGoalPose() const {
  KJ_IREQUIRE((which() == Action::GOAL_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Pose::Builder Action::Builder::getGoalPose() {
  KJ_IREQUIRE((which() == Action::GOAL_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::setGoalPose( ::vpp_msg::Pose::Reader value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::GOAL_POSE);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Pose::Builder Action::Builder::initGoalPose() {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::GOAL_POSE);
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::adoptGoalPose(
    ::capnp::Orphan< ::vpp_msg::Pose>&& value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::GOAL_POSE);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Pose> Action::Builder::disownGoalPose() {
  KJ_IREQUIRE((which() == Action::GOAL_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Action::Reader::isRelativePose() const {
  return which() == Action::RELATIVE_POSE;
}
inline bool Action::Builder::isRelativePose() {
  return which() == Action::RELATIVE_POSE;
}
inline bool Action::Reader::hasRelativePose() const {
  if (which() != Action::RELATIVE_POSE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Action::Builder::hasRelativePose() {
  if (which() != Action::RELATIVE_POSE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Pose::Reader Action::Reader::getRelativePose() const {
  KJ_IREQUIRE((which() == Action::RELATIVE_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Pose::Builder Action::Builder::getRelativePose() {
  KJ_IREQUIRE((which() == Action::RELATIVE_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::setRelativePose( ::vpp_msg::Pose::Reader value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_POSE);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Pose::Builder Action::Builder::initRelativePose() {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_POSE);
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::adoptRelativePose(
    ::capnp::Orphan< ::vpp_msg::Pose>&& value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RELATIVE_POSE);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Pose> Action::Builder::disownRelativePose() {
  KJ_IREQUIRE((which() == Action::RELATIVE_POSE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Action::Reader::isResetAndRandomize() const {
  return which() == Action::RESET_AND_RANDOMIZE;
}
inline bool Action::Builder::isResetAndRandomize() {
  return which() == Action::RESET_AND_RANDOMIZE;
}
inline bool Action::Reader::hasResetAndRandomize() const {
  if (which() != Action::RESET_AND_RANDOMIZE) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Action::Builder::hasResetAndRandomize() {
  if (which() != Action::RESET_AND_RANDOMIZE) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::RandomizationParameters::Reader Action::Reader::getResetAndRandomize() const {
  KJ_IREQUIRE((which() == Action::RESET_AND_RANDOMIZE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::RandomizationParameters::Builder Action::Builder::getResetAndRandomize() {
  KJ_IREQUIRE((which() == Action::RESET_AND_RANDOMIZE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::setResetAndRandomize( ::vpp_msg::RandomizationParameters::Reader value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RESET_AND_RANDOMIZE);
  ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::RandomizationParameters::Builder Action::Builder::initResetAndRandomize() {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RESET_AND_RANDOMIZE);
  return ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Action::Builder::adoptResetAndRandomize(
    ::capnp::Orphan< ::vpp_msg::RandomizationParameters>&& value) {
  _builder.setDataField<Action::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, Action::RESET_AND_RANDOMIZE);
  ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::RandomizationParameters> Action::Builder::disownResetAndRandomize() {
  KJ_IREQUIRE((which() == Action::RESET_AND_RANDOMIZE),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::RandomizationParameters>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

}  // namespace

