@0xb6359c08aa155a42;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

using import "pose.capnp".Pose;

struct Observation {
  unknownCount @0 :List(UInt32);
  freeCount @1 :List(UInt32);
  occupiedCount @2 :List(UInt32);
  roiCount @3 :List(UInt32);

  width @4 :UInt32;
  height @5 :UInt32;
  layers @6 :UInt32;

  foundRois @7 :UInt32;
  planningTime @8 :Float64;

  robotPose @9 :Pose;
  robotJoints @10 :List(Float64);
}
