// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: observation.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 7000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "pointcloud.capnp.h"
#include "pose.capnp.h"
#include "voxelgrid.capnp.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(d3d920ef8fc94d08);
CAPNP_DECLARE_SCHEMA(f8aa7bb7b3aafd0c);
CAPNP_DECLARE_SCHEMA(d37a82c6120ef713);

}  // namespace schemas
}  // namespace capnp

namespace vpp_msg {

struct Observation {
  Observation() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Map;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d3d920ef8fc94d08, 6, 6)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Observation::Map {
  Map() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    COUNT_MAP,
    POINTCLOUD,
    VOXELGRID,
    FULL_VOXELGRID,
  };
  struct CountMap;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f8aa7bb7b3aafd0c, 6, 6)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct Observation::Map::CountMap {
  CountMap() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d37a82c6120ef713, 6, 6)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Observation::Reader {
public:
  typedef Observation Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename Map::Reader getMap() const;

  inline  ::uint32_t getFoundRois() const;

  inline double getPlanningTime() const;

  inline bool hasRobotPose() const;
  inline  ::vpp_msg::Pose::Reader getRobotPose() const;

  inline bool hasRobotJoints() const;
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader getRobotJoints() const;

  inline  ::uint32_t getTotalRoiCells() const;

  inline double getEvalTotalTrajectoryDuration() const;

  inline  ::uint32_t getFoundFree() const;

  inline  ::uint32_t getFoundOcc() const;

  inline bool getHasMoved() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Observation::Builder {
public:
  typedef Observation Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename Map::Builder getMap();
  inline typename Map::Builder initMap();

  inline  ::uint32_t getFoundRois();
  inline void setFoundRois( ::uint32_t value);

  inline double getPlanningTime();
  inline void setPlanningTime(double value);

  inline bool hasRobotPose();
  inline  ::vpp_msg::Pose::Builder getRobotPose();
  inline void setRobotPose( ::vpp_msg::Pose::Reader value);
  inline  ::vpp_msg::Pose::Builder initRobotPose();
  inline void adoptRobotPose(::capnp::Orphan< ::vpp_msg::Pose>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Pose> disownRobotPose();

  inline bool hasRobotJoints();
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder getRobotJoints();
  inline void setRobotJoints( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setRobotJoints(::kj::ArrayPtr<const double> value);
  inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder initRobotJoints(unsigned int size);
  inline void adoptRobotJoints(::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> disownRobotJoints();

  inline  ::uint32_t getTotalRoiCells();
  inline void setTotalRoiCells( ::uint32_t value);

  inline double getEvalTotalTrajectoryDuration();
  inline void setEvalTotalTrajectoryDuration(double value);

  inline  ::uint32_t getFoundFree();
  inline void setFoundFree( ::uint32_t value);

  inline  ::uint32_t getFoundOcc();
  inline void setFoundOcc( ::uint32_t value);

  inline bool getHasMoved();
  inline void setHasMoved(bool value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Observation::Pipeline {
public:
  typedef Observation Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename Map::Pipeline getMap();
  inline  ::vpp_msg::Pose::Pipeline getRobotPose();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Observation::Map::Reader {
public:
  typedef Map Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isCountMap() const;
  inline typename CountMap::Reader getCountMap() const;

  inline bool isPointcloud() const;
  inline bool hasPointcloud() const;
  inline  ::vpp_msg::Pointcloud::Reader getPointcloud() const;

  inline bool isVoxelgrid() const;
  inline bool hasVoxelgrid() const;
  inline  ::vpp_msg::Voxelgrid::Reader getVoxelgrid() const;

  inline bool isFullVoxelgrid() const;
  inline bool hasFullVoxelgrid() const;
  inline  ::vpp_msg::Voxelgrid::Reader getFullVoxelgrid() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Observation::Map::Builder {
public:
  typedef Map Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isCountMap();
  inline typename CountMap::Builder getCountMap();
  inline typename CountMap::Builder initCountMap();

  inline bool isPointcloud();
  inline bool hasPointcloud();
  inline  ::vpp_msg::Pointcloud::Builder getPointcloud();
  inline void setPointcloud( ::vpp_msg::Pointcloud::Reader value);
  inline  ::vpp_msg::Pointcloud::Builder initPointcloud();
  inline void adoptPointcloud(::capnp::Orphan< ::vpp_msg::Pointcloud>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Pointcloud> disownPointcloud();

  inline bool isVoxelgrid();
  inline bool hasVoxelgrid();
  inline  ::vpp_msg::Voxelgrid::Builder getVoxelgrid();
  inline void setVoxelgrid( ::vpp_msg::Voxelgrid::Reader value);
  inline  ::vpp_msg::Voxelgrid::Builder initVoxelgrid();
  inline void adoptVoxelgrid(::capnp::Orphan< ::vpp_msg::Voxelgrid>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Voxelgrid> disownVoxelgrid();

  inline bool isFullVoxelgrid();
  inline bool hasFullVoxelgrid();
  inline  ::vpp_msg::Voxelgrid::Builder getFullVoxelgrid();
  inline void setFullVoxelgrid( ::vpp_msg::Voxelgrid::Reader value);
  inline  ::vpp_msg::Voxelgrid::Builder initFullVoxelgrid();
  inline void adoptFullVoxelgrid(::capnp::Orphan< ::vpp_msg::Voxelgrid>&& value);
  inline ::capnp::Orphan< ::vpp_msg::Voxelgrid> disownFullVoxelgrid();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Observation::Map::Pipeline {
public:
  typedef Map Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class Observation::Map::CountMap::Reader {
public:
  typedef CountMap Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool hasUnknownCount() const;
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader getUnknownCount() const;

  inline bool hasFreeCount() const;
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader getFreeCount() const;

  inline bool hasOccupiedCount() const;
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader getOccupiedCount() const;

  inline bool hasRoiCount() const;
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader getRoiCount() const;

  inline  ::uint32_t getWidth() const;

  inline  ::uint32_t getHeight() const;

  inline  ::uint32_t getLayers() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Observation::Map::CountMap::Builder {
public:
  typedef CountMap Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasUnknownCount();
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder getUnknownCount();
  inline void setUnknownCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setUnknownCount(::kj::ArrayPtr<const  ::uint32_t> value);
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder initUnknownCount(unsigned int size);
  inline void adoptUnknownCount(::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> disownUnknownCount();

  inline bool hasFreeCount();
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder getFreeCount();
  inline void setFreeCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setFreeCount(::kj::ArrayPtr<const  ::uint32_t> value);
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder initFreeCount(unsigned int size);
  inline void adoptFreeCount(::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> disownFreeCount();

  inline bool hasOccupiedCount();
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder getOccupiedCount();
  inline void setOccupiedCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setOccupiedCount(::kj::ArrayPtr<const  ::uint32_t> value);
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder initOccupiedCount(unsigned int size);
  inline void adoptOccupiedCount(::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> disownOccupiedCount();

  inline bool hasRoiCount();
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder getRoiCount();
  inline void setRoiCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value);
  inline void setRoiCount(::kj::ArrayPtr<const  ::uint32_t> value);
  inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder initRoiCount(unsigned int size);
  inline void adoptRoiCount(::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> disownRoiCount();

  inline  ::uint32_t getWidth();
  inline void setWidth( ::uint32_t value);

  inline  ::uint32_t getHeight();
  inline void setHeight( ::uint32_t value);

  inline  ::uint32_t getLayers();
  inline void setLayers( ::uint32_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Observation::Map::CountMap::Pipeline {
public:
  typedef CountMap Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline typename Observation::Map::Reader Observation::Reader::getMap() const {
  return typename Observation::Map::Reader(_reader);
}
inline typename Observation::Map::Builder Observation::Builder::getMap() {
  return typename Observation::Map::Builder(_builder);
}
#if !CAPNP_LITE
inline typename Observation::Map::Pipeline Observation::Pipeline::getMap() {
  return typename Observation::Map::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename Observation::Map::Builder Observation::Builder::initMap() {
  _builder.setDataField< ::uint32_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint32_t>(::capnp::bounded<1>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint32_t>(::capnp::bounded<2>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint16_t>(::capnp::bounded<14>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<2>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<3>() * ::capnp::POINTERS).clear();
  return typename Observation::Map::Builder(_builder);
}
inline  ::uint32_t Observation::Reader::getFoundRois() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Builder::getFoundRois() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setFoundRois( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<3>() * ::capnp::ELEMENTS, value);
}

inline double Observation::Reader::getPlanningTime() const {
  return _reader.getDataField<double>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline double Observation::Builder::getPlanningTime() {
  return _builder.getDataField<double>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setPlanningTime(double value) {
  _builder.setDataField<double>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

inline bool Observation::Reader::hasRobotPose() const {
  return !_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Builder::hasRobotPose() {
  return !_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Pose::Reader Observation::Reader::getRobotPose() const {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_reader.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Pose::Builder Observation::Builder::getRobotPose() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::get(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::vpp_msg::Pose::Pipeline Observation::Pipeline::getRobotPose() {
  return  ::vpp_msg::Pose::Pipeline(_typeless.getPointerField(4));
}
#endif  // !CAPNP_LITE
inline void Observation::Builder::setRobotPose( ::vpp_msg::Pose::Reader value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::set(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Pose::Builder Observation::Builder::initRobotPose() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::init(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}
inline void Observation::Builder::adoptRobotPose(
    ::capnp::Orphan< ::vpp_msg::Pose>&& value) {
  ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::adopt(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Pose> Observation::Builder::disownRobotPose() {
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pose>::disown(_builder.getPointerField(
      ::capnp::bounded<4>() * ::capnp::POINTERS));
}

inline bool Observation::Reader::hasRobotJoints() const {
  return !_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Builder::hasRobotJoints() {
  return !_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader Observation::Reader::getRobotJoints() const {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Builder::getRobotJoints() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}
inline void Observation::Builder::setRobotJoints( ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), value);
}
inline void Observation::Builder::setRobotJoints(::kj::ArrayPtr<const double> value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Builder::initRobotJoints(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), size);
}
inline void Observation::Builder::adoptRobotJoints(
    ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>> Observation::Builder::disownRobotJoints() {
  return ::capnp::_::PointerHelpers< ::capnp::List<double,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<5>() * ::capnp::POINTERS));
}

inline  ::uint32_t Observation::Reader::getTotalRoiCells() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Builder::getTotalRoiCells() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setTotalRoiCells( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<6>() * ::capnp::ELEMENTS, value);
}

inline double Observation::Reader::getEvalTotalTrajectoryDuration() const {
  return _reader.getDataField<double>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}

inline double Observation::Builder::getEvalTotalTrajectoryDuration() {
  return _builder.getDataField<double>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setEvalTotalTrajectoryDuration(double value) {
  _builder.setDataField<double>(
      ::capnp::bounded<4>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Observation::Reader::getFoundFree() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<10>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Builder::getFoundFree() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<10>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setFoundFree( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<10>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Observation::Reader::getFoundOcc() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Builder::getFoundOcc() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setFoundOcc( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<11>() * ::capnp::ELEMENTS, value);
}

inline bool Observation::Reader::getHasMoved() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<240>() * ::capnp::ELEMENTS);
}

inline bool Observation::Builder::getHasMoved() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<240>() * ::capnp::ELEMENTS);
}
inline void Observation::Builder::setHasMoved(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<240>() * ::capnp::ELEMENTS, value);
}

inline  ::vpp_msg::Observation::Map::Which Observation::Map::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}
inline  ::vpp_msg::Observation::Map::Which Observation::Map::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS);
}

inline bool Observation::Map::Reader::isCountMap() const {
  return which() == Observation::Map::COUNT_MAP;
}
inline bool Observation::Map::Builder::isCountMap() {
  return which() == Observation::Map::COUNT_MAP;
}
inline typename Observation::Map::CountMap::Reader Observation::Map::Reader::getCountMap() const {
  KJ_IREQUIRE((which() == Observation::Map::COUNT_MAP),
              "Must check which() before get()ing a union member.");
  return typename Observation::Map::CountMap::Reader(_reader);
}
inline typename Observation::Map::CountMap::Builder Observation::Map::Builder::getCountMap() {
  KJ_IREQUIRE((which() == Observation::Map::COUNT_MAP),
              "Must check which() before get()ing a union member.");
  return typename Observation::Map::CountMap::Builder(_builder);
}
inline typename Observation::Map::CountMap::Builder Observation::Map::Builder::initCountMap() {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::COUNT_MAP);
  _builder.setDataField< ::uint32_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint32_t>(::capnp::bounded<1>() * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint32_t>(::capnp::bounded<2>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<1>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<2>() * ::capnp::POINTERS).clear();
  _builder.getPointerField(::capnp::bounded<3>() * ::capnp::POINTERS).clear();
  return typename Observation::Map::CountMap::Builder(_builder);
}
inline bool Observation::Map::Reader::isPointcloud() const {
  return which() == Observation::Map::POINTCLOUD;
}
inline bool Observation::Map::Builder::isPointcloud() {
  return which() == Observation::Map::POINTCLOUD;
}
inline bool Observation::Map::Reader::hasPointcloud() const {
  if (which() != Observation::Map::POINTCLOUD) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::Builder::hasPointcloud() {
  if (which() != Observation::Map::POINTCLOUD) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Pointcloud::Reader Observation::Map::Reader::getPointcloud() const {
  KJ_IREQUIRE((which() == Observation::Map::POINTCLOUD),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Pointcloud::Builder Observation::Map::Builder::getPointcloud() {
  KJ_IREQUIRE((which() == Observation::Map::POINTCLOUD),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::setPointcloud( ::vpp_msg::Pointcloud::Reader value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::POINTCLOUD);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Pointcloud::Builder Observation::Map::Builder::initPointcloud() {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::POINTCLOUD);
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::adoptPointcloud(
    ::capnp::Orphan< ::vpp_msg::Pointcloud>&& value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::POINTCLOUD);
  ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Pointcloud> Observation::Map::Builder::disownPointcloud() {
  KJ_IREQUIRE((which() == Observation::Map::POINTCLOUD),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Pointcloud>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Observation::Map::Reader::isVoxelgrid() const {
  return which() == Observation::Map::VOXELGRID;
}
inline bool Observation::Map::Builder::isVoxelgrid() {
  return which() == Observation::Map::VOXELGRID;
}
inline bool Observation::Map::Reader::hasVoxelgrid() const {
  if (which() != Observation::Map::VOXELGRID) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::Builder::hasVoxelgrid() {
  if (which() != Observation::Map::VOXELGRID) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Voxelgrid::Reader Observation::Map::Reader::getVoxelgrid() const {
  KJ_IREQUIRE((which() == Observation::Map::VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Voxelgrid::Builder Observation::Map::Builder::getVoxelgrid() {
  KJ_IREQUIRE((which() == Observation::Map::VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::setVoxelgrid( ::vpp_msg::Voxelgrid::Reader value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::VOXELGRID);
  ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Voxelgrid::Builder Observation::Map::Builder::initVoxelgrid() {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::VOXELGRID);
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::adoptVoxelgrid(
    ::capnp::Orphan< ::vpp_msg::Voxelgrid>&& value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::VOXELGRID);
  ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Voxelgrid> Observation::Map::Builder::disownVoxelgrid() {
  KJ_IREQUIRE((which() == Observation::Map::VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Observation::Map::Reader::isFullVoxelgrid() const {
  return which() == Observation::Map::FULL_VOXELGRID;
}
inline bool Observation::Map::Builder::isFullVoxelgrid() {
  return which() == Observation::Map::FULL_VOXELGRID;
}
inline bool Observation::Map::Reader::hasFullVoxelgrid() const {
  if (which() != Observation::Map::FULL_VOXELGRID) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::Builder::hasFullVoxelgrid() {
  if (which() != Observation::Map::FULL_VOXELGRID) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::vpp_msg::Voxelgrid::Reader Observation::Map::Reader::getFullVoxelgrid() const {
  KJ_IREQUIRE((which() == Observation::Map::FULL_VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::vpp_msg::Voxelgrid::Builder Observation::Map::Builder::getFullVoxelgrid() {
  KJ_IREQUIRE((which() == Observation::Map::FULL_VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::setFullVoxelgrid( ::vpp_msg::Voxelgrid::Reader value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::FULL_VOXELGRID);
  ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::vpp_msg::Voxelgrid::Builder Observation::Map::Builder::initFullVoxelgrid() {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::FULL_VOXELGRID);
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::Builder::adoptFullVoxelgrid(
    ::capnp::Orphan< ::vpp_msg::Voxelgrid>&& value) {
  _builder.setDataField<Observation::Map::Which>(
      ::capnp::bounded<14>() * ::capnp::ELEMENTS, Observation::Map::FULL_VOXELGRID);
  ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::vpp_msg::Voxelgrid> Observation::Map::Builder::disownFullVoxelgrid() {
  KJ_IREQUIRE((which() == Observation::Map::FULL_VOXELGRID),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::vpp_msg::Voxelgrid>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Observation::Map::CountMap::Reader::hasUnknownCount() const {
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::CountMap::Builder::hasUnknownCount() {
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader Observation::Map::CountMap::Reader::getUnknownCount() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::getUnknownCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Observation::Map::CountMap::Builder::setUnknownCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline void Observation::Map::CountMap::Builder::setUnknownCount(::kj::ArrayPtr<const  ::uint32_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::initUnknownCount(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Observation::Map::CountMap::Builder::adoptUnknownCount(
    ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> Observation::Map::CountMap::Builder::disownUnknownCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool Observation::Map::CountMap::Reader::hasFreeCount() const {
  return !_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::CountMap::Builder::hasFreeCount() {
  return !_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader Observation::Map::CountMap::Reader::getFreeCount() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::getFreeCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}
inline void Observation::Map::CountMap::Builder::setFreeCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline void Observation::Map::CountMap::Builder::setFreeCount(::kj::ArrayPtr<const  ::uint32_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::initFreeCount(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), size);
}
inline void Observation::Map::CountMap::Builder::adoptFreeCount(
    ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> Observation::Map::CountMap::Builder::disownFreeCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<1>() * ::capnp::POINTERS));
}

inline bool Observation::Map::CountMap::Reader::hasOccupiedCount() const {
  return !_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::CountMap::Builder::hasOccupiedCount() {
  return !_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader Observation::Map::CountMap::Reader::getOccupiedCount() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::getOccupiedCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}
inline void Observation::Map::CountMap::Builder::setOccupiedCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline void Observation::Map::CountMap::Builder::setOccupiedCount(::kj::ArrayPtr<const  ::uint32_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::initOccupiedCount(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), size);
}
inline void Observation::Map::CountMap::Builder::adoptOccupiedCount(
    ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> Observation::Map::CountMap::Builder::disownOccupiedCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<2>() * ::capnp::POINTERS));
}

inline bool Observation::Map::CountMap::Reader::hasRoiCount() const {
  return !_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline bool Observation::Map::CountMap::Builder::hasRoiCount() {
  return !_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader Observation::Map::CountMap::Reader::getRoiCount() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_reader.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::getRoiCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::get(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}
inline void Observation::Map::CountMap::Builder::setRoiCount( ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline void Observation::Map::CountMap::Builder::setRoiCount(::kj::ArrayPtr<const  ::uint32_t> value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::set(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>::Builder Observation::Map::CountMap::Builder::initRoiCount(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::init(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), size);
}
inline void Observation::Map::CountMap::Builder::adoptRoiCount(
    ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::adopt(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>> Observation::Map::CountMap::Builder::disownRoiCount() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::uint32_t,  ::capnp::Kind::PRIMITIVE>>::disown(_builder.getPointerField(
      ::capnp::bounded<3>() * ::capnp::POINTERS));
}

inline  ::uint32_t Observation::Map::CountMap::Reader::getWidth() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Map::CountMap::Builder::getWidth() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Observation::Map::CountMap::Builder::setWidth( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Observation::Map::CountMap::Reader::getHeight() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Map::CountMap::Builder::getHeight() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS);
}
inline void Observation::Map::CountMap::Builder::setHeight( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<1>() * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t Observation::Map::CountMap::Reader::getLayers() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Observation::Map::CountMap::Builder::getLayers() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline void Observation::Map::CountMap::Builder::setLayers( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, value);
}

}  // namespace

