@0xcefb0169decdaccb;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

struct Pointcloud {
  points @0 :List(Float32);
  labels @1 :List(UInt8);
}
