@0x8dc6e29d8ba42c62;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

struct PointcloudOld {
  points @0 :List(Float64);
  labels @1 :List(Int64);
}
