@0x8a9b31aa487572fd;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

struct Point {
  x @0 :Float64;
  y @1 :Float64;
  z @2 :Float64;
}

struct Quaternion {
  x @0 :Float64;
  y @1 :Float64;
  z @2 :Float64;
  w @3 :Float64;
}

struct Pose {
  position @0 :Point;
  orientation @1 :Quaternion;
}
