@0xd9806c76861912e3;  # unique file ID, generated by `capnp id`

using Cxx = import "/capnp/c++.capnp";
$Cxx.namespace("vpp_msg");

struct Voxelgrid {
  labels @0 :List(UInt8);
  shape @1 :List(UInt16);
  center @2 :List(Float32);
  resolution @3 :Float32;
}
