ReplayBuffer:
  capacity : 40000
  num_steps : 3

PrioritizedReplayBuffer:
  capacity : 40000
  num_steps : 3
  alpha : 0.6
  beta0 : 0.4
  # Anneal beta from beta0 to 1 throughout training
  betasteps : 200000
  normalize_by_max : memory
