
# train
# gpu >=0 : use gpu;
# gpu <0 : use cpu
gpu: -1
debug_mode: False
num_episodes_to_run: 10000000
save_model_every_n: 1000

bl_console_logging_level: WARNING
bl_file_logging_level: WARNING
smooth_n: 100

# choose from [NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL]
logging_level: WARNING
# out_parent_folder
out_parent_folder: "output"

# out
out_folder: ""

out_model: "model"
out_log: "log"

# in
in_folder: ""

in_model: "model"