# train
# gpu >=0 : use gpu;
# gpu <0 : use cpu
gpu: -1
debug_mode: False
num_episodes_to_run: 10000000
save_model_every_n: 100
save_result_n: 1000

bl_console_logging_level: WARNING
bl_file_logging_level: WARNING
smooth_n: 100

# choose from [NOTSET, DEBUG, INFO, WARNING, ERROR, CRITICAL]
logging_level: WARNING

train: None
# parameters (out_folder, in_folder, in_model_index, train) are given by  argparse

#reward weight
rewards:
  visit_gain_weight: 0
  new_found_targets_weight: 1
  new_free_cells_weight: 0.01

# 1 : true; 0: false
input:
  observation_map: 1
  visit_map: 0

network:
  NetworkObs: 0
  NetworkVisit: 0
  NetworkVisitTemporal: 0
  NetworkObsTemporal: 1
  SpatialAttentionModel: 0

action:
  ActionMoRo10: 1
  ActionMoRoMultiplier30: 0

